Add release notes and new tests

diff --git a/ci/settings.yml b/ci/settings.yml
--- a/ci/settings.yml
+++ b/ci/settings.yml
@@ -249,6 +249,57 @@ jobs:
                     failure="true"
                 fi
 
+
+
+                version_family="3.0"
+
+                latest_version_json=$(
+                    jq --null-input \
+                            --arg "family" "${version_family}" \
+                            '{ "source": { "family": $family } }' \
+                        | /opt/resource/check
+                )
+                latest_version=$(jq --raw-output '.[0].version' <<< "${latest_version_json}")
+
+                if [[ ${latest_version} != ${version_family}* ]]; then
+                    echo >&2 "FAIL: expected version to start with '${version_family}', but got '${latest_version}'."
+                    failure="true"
+                fi
+
+
+
+                version_family="3.1"
+
+                latest_version_json=$(
+                    jq --null-input \
+                            --arg "family" "${version_family}" \
+                            '{ "source": { "family": $family } }' \
+                        | /opt/resource/check
+                )
+                latest_version=$(jq --raw-output '.[0].version' <<< "${latest_version_json}")
+
+                if [[ ${latest_version} != ${version_family}* ]]; then
+                    echo >&2 "FAIL: expected version to start with '${version_family}', but got '${latest_version}'."
+                    failure="true"
+                fi
+
+
+
+                version_family="3.2"
+
+                latest_version_json=$(
+                    jq --null-input \
+                            --arg "family" "${version_family}" \
+                            '{ "source": { "family": $family } }' \
+                        | /opt/resource/check
+                )
+                latest_version=$(jq --raw-output '.[0].version' <<< "${latest_version_json}")
+
+                if [[ ${latest_version} != ${version_family}* ]]; then
+                    echo >&2 "FAIL: expected version to start with '${version_family}', but got '${latest_version}'."
+                    failure="true"
+                fi
+
                 if [[ ${failure} == true ]]; then
                     exit 1
                 fi
